spring:
  application:
    name: itoken-admin
  zipkin:
    base-url: http://192.168.198.136:9411

server:
  port: 8084

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.198.136:8761/eureka/