spring:
  application:
    name: itoken-eureka
  zipkin:
    base-url: http://192.168.198.136:9411
  boot:
    admin:
      client:
        url: http://192.168.198.136:8084

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.198.136:8761/eureka/,http://192.168.198.136:8861/eureka/,http://192.168.198.136:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info