spring:
  application:
    name: itoken-web-admin
  zipkin:
    base-url: http://192.168.198.131:9411
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: LEGACYHTML5 # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

feign:
  hystrix:
    enabled: true


server:
  port: 8601

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.198.136:8761/eureka/